// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  buildDiscordComponentMessage,
  collectDiscordStatusIssues,
  createDiscordActionGate,
  handleDiscordMessageAction,
  inspectDiscordAccount,
  isDiscordExecApprovalClientEnabled,
  listDiscordAccountIds,
  listDiscordDirectoryGroupsFromConfig,
  listDiscordDirectoryPeersFromConfig,
  looksLikeDiscordTargetId,
  normalizeDiscordMessagingTarget,
  normalizeDiscordOutboundTarget,
  readDiscordComponentSpec,
  resolveDefaultDiscordAccountId,
  resolveDiscordAccount,
  resolveDiscordChannelId,
  resolveDiscordRuntimeGroupPolicy,
  resolveDiscordGroupRequireMention,
  resolveDiscordGroupToolPolicy,
} from "../../extensions/discord/api.js";

// Compatibility fallback: older callers import this helper from plugin-sdk.
// Upstream now resolves approver checks via runtime-specific plumbing.
export function isDiscordExecApprovalApprover(_ctx: unknown): boolean {
  return false;
}
export type {
  DiscordComponentMessageSpec,
  DiscordProbe,
  DiscordSendComponents,
  DiscordSendEmbeds,
  DiscordSendResult,
  DiscordTokenResolution,
  InspectedDiscordAccount,
  ResolvedDiscordAccount,
} from "../../extensions/discord/api.js";
